const course_list=[
    {
        'id':1,
        'course_name':"Physics",
        'category_id':2,
        'department_id':4,
        'credit_hour':4,
        "grade":10,
        'created_at':'2022-03-23'
    },
    {
        'id':2,
        'course_name':"Chemistry",
        'department_id':7,
        'category_id':2,
        'credit_hour':4,
        "grade":10,
        'created_at':'2022-03-20'
    },
    {
        'id':3,
        'course_name':"Physics",
        'department_id':4,
        'category_id':2,
        'credit_hour':4,
        "grade":11,
        'created_at':'2022-03-12'
    },{
        'id':4,
        'course_name':"Mathematics",
        'department_id':3,
        'category_id':2,
        'credit_hour':4,
        "grade":9,
        'created_at':'2022-03-21'
    },{
        'id':5,
        'course_name':"Chemistry",
        'department_id':7,
        'category_id':2,
        'credit_hour':4,
        "grade":11,
        'created_at':'2022-03-23'
    },
    {
        'id':6,
        'course_name':"Chemistry",
        'department_id':7,
        'category_id':2,
        'credit_hour':4,
        "grade":11,
        'created_at':'2022-03-23'
    },
    {
        'id':7,
        'course_name':"Amharic",
        'department_id':1,
        'category_id':2,
        'credit_hour':3,
        "grade":11,
        'created_at':'2022-03-23'
    },
    {
        'id':8,
        'course_name':"Amharic",
        'department_id':1,
        'category_id':1,
        'credit_hour':3,
        "grade":9,
        'created_at':'2022-03-23'
    },
    {
        'id':9,
        'course_name':"Amharic",
        'department_id':1,
        'category_id':1,
        'credit_hour':3,
        "grade":12,
        'created_at':'2022-03-23'
    },
    {
        'id':10,
        'course_name':"English",
        'department_id':2,
        'category_id':1,
        "grade":12,
        'created_at':'2022-03-23'
    }

]