const section =[
    {
        'id':1,
        'section_name':'A',
        "year":2022,
        "building":"A-Block",
        'grade':12,
        "room_number":4,
        'section_respondent_teacher_id':23,
        'section_respondent_student_id':3,
        'section_vice_respondent_student_id':6,
        'created_at':'2023-09-45'
    },

    {
        'id':2,
        'section_name':'B',
        'grade':10,
        "year":2022,
        "building":"A-Block",
        "room_number":5,
        'section_respondent_teacher_id':3,
        'section_respondent_student_id':37,
        'section_vice_respondent_student_id':86,
        'created_at':'2023-09-45'
    },

    {
        'id':3,
        'section_name':'A',
        "year":2022,
        "building":"A-Block",
        'grade':12,
        "room_number":7,
        'section_respondent_teacher_id':13,
        'section_respondent_student_id':63,
        'section_vice_respondent_student_id':69,
        'created_at':'2023-09-45'
    },

    {
        'id':4,
        'section_name':'C',
        "semister_id":1,
        'grade':11,
        "year":2022,
        "building":"A-Block",
        "room_number":9,
        'section_respondent_teacher_id':43,
        'section_respondent_student_id':33,
        'section_vice_respondent_student_id':56,
        'created_at':'2023-09-45'
    },
    {
        'id':4,
        'section_name':'C',
        "semister_id":1,
        'grade':10,
        "year":2022,
        "building":"A-Block",
        "room_number":9,
        'section_respondent_teacher_id':43,
        'section_respondent_student_id':33,
        'section_vice_respondent_student_id':56,
        'created_at':'2023-09-45'
    }
]