import users from "./user";

const TeacherList =[
    {
        id:1,
        username:"DAR/1123/15",
        profile_pic: "/assets/images/avatars/avatar_1.jpg",
        religion:'orthodox',
        gender:"male",
        department:4,
        major:"Major",
        minor:"Minor",
        degree:"BA",
        cgpa:"3.56",
        college:"Standard college",
        qualification:"Linear",
        experience:2,
        salary:6789.23,
        contract_type:"PERMANENT",
        tin_number:"007875432",
        phone:"+2519235678",
        emergency_phone:"+2519567823",
        marital_status:"single",
        current_address:1,
        permanent_address:2,
        bank_account:1,
        facebook_account:"facebook url",
        twitter_account:"twitter url",
        linkedin_account:"linkedin url",
        instagram_account:"instagram url",
        date_of_birth:"2000-03-12",
        birth_place:"Addis Ababa",
        status:"banned",
        role:1,
        updated_at: "2023-05-12",
        created_at:"2022-01-23"


    },
    {
        id:2,
        username:"DAR/1124/15",
        profile_pic: "/assets/images/avatars/avatar_2.jpg",
        religion:'orthodox',
        gender:"male",
        department:4,
        major:"Major",
        minor:"Minor",
        degree:"BA",
        cgpa:"3.56",
        college:"Standard college",
        qualification:"Linear",
        experience:2,
        salary:6789.23,
        contract_type:"PERMANENT",
        tin_number:"007875432",
        phone:"+2519235678",
        emergency_phone:"+2519567823",
        marital_status:"single",
        current_address:1,
        permanent_address:2,
        bank_account:1,
        facebook_account:"facebook url",
        twitter_account:"twitter url",
        linkedin_account:"linkedin url",
        instagram_account:"instagram url",
        date_of_birth:"2000-03-12",
        birth_place:"Addis Ababa",
        status:"banned",
        role:1,
        updated_at: "2023-05-12",
        created_at:"2022-01-23"


    },
    {
        id:3,
        username:"DAR/1125/15",
        profile_pic: "/assets/images/avatars/avatar_3.jpg",
        religion:'orthodox',
        gender:"male",
        department:4,
        major:"Major",
        minor:"Minor",
        degree:"BA",
        cgpa:"3.56",
        college:"Standard college",
        qualification:"Linear",
        experience:2,
        salary:6789.23,
        contract_type:"PERMANENT",
        tin_number:"007875432",
        phone:"+2519235678",
        emergency_phone:"+2519567823",
        marital_status:"single",
        current_address:1,
        permanent_address:2,
        bank_account:1,
        facebook_account:"facebook url",
        twitter_account:"twitter url",
        linkedin_account:"linkedin url",
        instagram_account:"instagram url",
        date_of_birth:"2000-03-12",
        birth_place:"Addis Ababa",
        status:"banned",
        role:1,
        updated_at: "2023-05-12",
        created_at:"2022-01-23"


    },
    {
        id:4,
        username:"DAR/1126/15",
        profile_pic: "/assets/images/avatars/avatar_4.jpg",
        religion:'orthodox',
        gender:"male",
        department:4,
        major:"Major",
        minor:"Minor",
        degree:"BA",
        cgpa:"3.56",
        college:"Standard college",
        qualification:"Linear",
        experience:2,
        salary:6789.23,
        contract_type:"PERMANENT",
        tin_number:"007875432",
        phone:"+2519235678",
        emergency_phone:"+2519567823",
        marital_status:"single",
        current_address:1,
        permanent_address:2,
        bank_account:1,
        facebook_account:"facebook url",
        twitter_account:"twitter url",
        linkedin_account:"linkedin url",
        instagram_account:"instagram url",
        date_of_birth:"2000-03-12",
        birth_place:"Addis Ababa",
        status:"banned",
        role:1,
        updated_at: "2023-05-12",
        created_at:"2022-01-23"


    },
    {
        id:5,
        username:"DAR/1127/15",
        profile_pic: "/assets/images/avatars/avatar_5.jpg",
        religion:'orthodox',
        gender:"male",
        department:4,
        major:"Major",
        minor:"Minor",
        degree:"BA",
        cgpa:"3.56",
        college:"Standard college",
        qualification:"Linear",
        experience:2,
        salary:6789.23,
        contract_type:"PERMANENT",
        tin_number:"007875432",
        phone:"+2519235678",
        emergency_phone:"+2519567823",
        marital_status:"single",
        current_address:1,
        permanent_address:2,
        bank_account:1,
        facebook_account:"facebook url",
        twitter_account:"twitter url",
        linkedin_account:"linkedin url",
        instagram_account:"instagram url",
        date_of_birth:"2000-03-12",
        birth_place:"Addis Ababa",
        status:"banned",
        role:1,
        updated_at: "2023-05-12",
        created_at:"2022-01-23"


    },
    {
        id:6,
        username:"DAR/1128/15",
        profile_pic: "/assets/images/avatars/avatar_6.jpg",
        religion:'orthodox',
        gender:"male",
        department:4,
        major:"Major",
        minor:"Minor",
        degree:"BA",
        cgpa:"3.56",
        college:"Standard college",
        qualification:"Linear",
        experience:2,
        salary:6789.23,
        contract_type:"PERMANENT",
        tin_number:"007875432",
        phone:"+2519235678",
        emergency_phone:"+2519567823",
        marital_status:"single",
        current_address:1,
        permanent_address:2,
        bank_account:1,
        facebook_account:"facebook url",
        twitter_account:"twitter url",
        linkedin_account:"linkedin url",
        instagram_account:"instagram url",
        date_of_birth:"2000-03-12",
        birth_place:"Addis Ababa",
        status:"banned",
        role:1,
        updated_at: "2023-05-12",
        created_at:"2022-01-23"


    },
    {
        id:7,
        username:"DAR/1129/15",
        profile_pic: "/assets/images/avatars/avatar_7.jpg",
        religion:'orthodox',
        gender:"male",
        department:4,
        major:"Major",
        minor:"Minor",
        degree:"BA",
        cgpa:"3.56",
        college:"Standard college",
        qualification:"Linear",
        experience:2,
        salary:6789.23,
        contract_type:"PERMANENT",
        tin_number:"007875432",
        phone:"+2519235678",
        emergency_phone:"+2519567823",
        marital_status:"single",
        current_address:1,
        permanent_address:2,
        bank_account:1,
        facebook_account:"facebook url",
        twitter_account:"twitter url",
        linkedin_account:"linkedin url",
        instagram_account:"instagram url",
        date_of_birth:"2000-03-12",
        birth_place:"Addis Ababa",
        status:"banned",
        role:1,
        updated_at: "2023-05-12",
        created_at:"2022-01-23"


    },
    {
        id:8,
        username:"DAR/1130/15",
        profile_pic: "/assets/images/avatars/avatar_8.jpg",
        religion:'orthodox',
        gender:"male",
        department:4,
        major:"Major",
        minor:"Minor",
        degree:"BA",
        cgpa:"3.56",
        college:"Standard college",
        qualification:"Linear",
        experience:2,
        salary:6789.23,
        contract_type:"PERMANENT",
        tin_number:"007875432",
        phone:"+2519235678",
        emergency_phone:"+2519567823",
        marital_status:"single",
        current_address:1,
        permanent_address:2,
        bank_account:1,
        facebook_account:"facebook url",
        twitter_account:"twitter url",
        linkedin_account:"linkedin url",
        instagram_account:"instagram url",
        date_of_birth:"2000-03-12",
        birth_place:"Addis Ababa",
        status:"banned",
        role:1,
        updated_at: "2023-05-12",
        created_at:"2022-01-23"


    },
    {
        id:9,
        username:"DAR/1131/15",
        profile_pic: "/assets/images/avatars/avatar_9.jpg",
        religion:'orthodox',
        gender:"male",
        department:4,
        major:"Major",
        minor:"Minor",
        degree:"BA",
        cgpa:"3.56",
        college:"Standard college",
        qualification:"Linear",
        experience:2,
        salary:6789.23,
        contract_type:"PERMANENT",
        tin_number:"007875432",
        phone:"+2519235678",
        emergency_phone:"+2519567823",
        marital_status:"single",
        current_address:1,
        permanent_address:2,
        bank_account:1,
        facebook_account:"facebook url",
        twitter_account:"twitter url",
        linkedin_account:"linkedin url",
        instagram_account:"instagram url",
        date_of_birth:"2000-03-12",
        birth_place:"Addis Ababa",
        status:"banned",
        role:1,
        updated_at: "2023-05-12",
        created_at:"2022-01-23"


    },
    {
        id:10,
        username:"DAR/1132/15",
        profile_pic: "/assets/images/avatars/avatar_10.jpg",
        religion:'orthodox',
        gender:"male",
        department:4,
        major:"Major",
        minor:"Minor",
        degree:"BA",
        cgpa:"3.56",
        college:"Standard college",
        qualification:"Linear",
        experience:2,
        salary:6789.23,
        contract_type:"PERMANENT",
        tin_number:"007875432",
        phone:"+2519235678",
        emergency_phone:"+2519567823",
        marital_status:"single",
        current_address:1,
        permanent_address:2,
        bank_account:1,
        facebook_account:"facebook url",
        twitter_account:"twitter url",
        linkedin_account:"linkedin url",
        instagram_account:"instagram url",
        date_of_birth:"2000-03-12",
        birth_place:"Addis Ababa",
        status:"banned",
        role:1,
        updated_at: "2023-05-12",
        created_at:"2022-01-23"


    },
    {
        id:11,
        username:"DAR/1133/15",
        profile_pic: "/assets/images/avatars/avatar_11.jpg",
        religion:'orthodox',
        gender:"male",
        department:4,
        major:"Major",
        minor:"Minor",
        degree:"BA",
        cgpa:"3.56",
        college:"Standard college",
        qualification:"Linear",
        experience:2,
        salary:6789.23,
        contract_type:"PERMANENT",
        tin_number:"007875432",
        phone:"+2519235678",
        emergency_phone:"+2519567823",
        marital_status:"single",
        current_address:1,
        permanent_address:2,
        bank_account:1,
        facebook_account:"facebook url",
        twitter_account:"twitter url",
        linkedin_account:"linkedin url",
        instagram_account:"instagram url",
        date_of_birth:"2000-03-12",
        birth_place:"Addis Ababa",
        status:"banned",
        role:1,
        updated_at: "2023-05-12",
        created_at:"2022-01-23"


    },
    {
        id:12,
        username:"DAR/1134/15",
        profile_pic: "/assets/images/avatars/avatar_18.jpg",
        religion:'orthodox',
        gender:"male",
        department:4,
        major:"Major",
        minor:"Minor",
        degree:"BA",
        cgpa:"3.56",
        college:"Standard college",
        qualification:"Linear",
        experience:2,
        salary:6789.23,
        contract_type:"PERMANENT",
        tin_number:"007875432",
        phone:"+2519235678",
        emergency_phone:"+2519567823",
        marital_status:"single",
        current_address:1,
        permanent_address:2,
        bank_account:1,
        facebook_account:"facebook url",
        twitter_account:"twitter url",
        linkedin_account:"linkedin url",
        instagram_account:"instagram url",
        date_of_birth:"2000-03-12",
        birth_place:"Addis Ababa",
        status:"banned",
        role:1,
        updated_at: "2023-05-12",
        created_at:"2022-01-23"


    },
    {
        id:13,
        username:"DAR/1135/15",
        profile_pic: "/assets/images/avatars/avatar_16.jpg",
        religion:'orthodox',
        gender:"male",
        department:4,
        major:"Major",
        minor:"Minor",
        degree:"BA",
        cgpa:"3.56",
        college:"Standard college",
        qualification:"Linear",
        experience:2,
        salary:6789.23,
        contract_type:"PERMANENT",
        tin_number:"007875432",
        phone:"+2519235678",
        emergency_phone:"+2519567823",
        marital_status:"single",
        current_address:1,
        permanent_address:2,
        bank_account:1,
        facebook_account:"facebook url",
        twitter_account:"twitter url",
        linkedin_account:"linkedin url",
        instagram_account:"instagram url",
        date_of_birth:"2000-03-12",
        birth_place:"Addis Ababa",
        status:"banned",
        role:1,
        updated_at: "2023-05-12",
        created_at:"2022-01-23"


    },
    {
        id:14,
        username:"DAR/1136/15",
        profile_pic: "/assets/images/avatars/avatar_17.jpg",
        religion:'orthodox',
        gender:"male",
        department:4,
        major:"Major",
        minor:"Minor",
        degree:"BA",
        cgpa:"3.56",
        college:"Standard college",
        qualification:"Linear",
        experience:2,
        salary:6789.23,
        contract_type:"PERMANENT",
        tin_number:"007875432",
        phone:"+2519235678",
        emergency_phone:"+2519567823",
        marital_status:"single",
        current_address:1,
        permanent_address:2,
        bank_account:1,
        facebook_account:"facebook url",
        twitter_account:"twitter url",
        linkedin_account:"linkedin url",
        instagram_account:"instagram url",
        date_of_birth:"2000-03-12",
        birth_place:"Addis Ababa",
        status:"banned",
        role:1,
        updated_at: "2023-05-12",
        created_at:"2022-01-23"


    },
    {
        id:15,
        username:"DAR/1137/15",
        profile_pic: "/assets/images/avatars/avatar_15.jpg",
        religion:'orthodox',
        gender:"male",
        department:4,
        major:"Major",
        minor:"Minor",
        degree:"BA",
        cgpa:"3.56",
        college:"Standard college",
        qualification:"Linear",
        experience:2,
        salary:6789.23,
        contract_type:"PERMANENT",
        tin_number:"007875432",
        phone:"+2519235678",
        emergency_phone:"+2519567823",
        marital_status:"single",
        current_address:1,
        permanent_address:2,
        bank_account:1,
        facebook_account:"facebook url",
        twitter_account:"twitter url",
        linkedin_account:"linkedin url",
        instagram_account:"instagram url",
        date_of_birth:"2000-03-12",
        birth_place:"Addis Ababa",
        status:"banned",
        role:1,
        updated_at: "2023-05-12",
        created_at:"2022-01-23"


    },
    {
        id:16,
        username:"DAR/1138/15",
        profile_pic: "/assets/images/avatars/avatar_22.jpg",
        religion:'orthodox',
        gender:"male",
        department:4,
        major:"Major",
        minor:"Minor",
        degree:"BA",
        cgpa:"3.56",
        college:"Standard college",
        qualification:"Linear",
        experience:2,
        salary:6789.23,
        contract_type:"PERMANENT",
        tin_number:"007875432",
        phone:"+2519235678",
        emergency_phone:"+2519567823",
        marital_status:"single",
        current_address:1,
        permanent_address:2,
        bank_account:1,
        facebook_account:"facebook url",
        twitter_account:"twitter url",
        linkedin_account:"linkedin url",
        instagram_account:"instagram url",
        date_of_birth:"2000-03-12",
        birth_place:"Addis Ababa",
        status:"banned",
        role:1,
        updated_at: "2023-05-12",
        created_at:"2022-01-23"


    },
    {
        id:17,
        username:"DAR/1139/15",
        profile_pic: "/assets/images/avatars/avatar_14.jpg",
        religion:'orthodox',
        gender:"male",
        department:4,
        major:"Major",
        minor:"Minor",
        degree:"BA",
        cgpa:"3.56",
        college:"Standard college",
        qualification:"Linear",
        experience:2,
        salary:6789.23,
        contract_type:"PERMANENT",
        tin_number:"007875432",
        phone:"+2519235678",
        emergency_phone:"+2519567823",
        marital_status:"single",
        current_address:1,
        permanent_address:2,
        bank_account:1,
        facebook_account:"facebook url",
        twitter_account:"twitter url",
        linkedin_account:"linkedin url",
        instagram_account:"instagram url",
        date_of_birth:"2000-03-12",
        birth_place:"Addis Ababa",
        status:"banned",
        role:1,
        updated_at: "2023-05-12",
        created_at:"2022-01-23"


    },
    {
        id:18,
        username:"DAR/1140/15",
        profile_pic: "/assets/images/avatars/avatar_13.jpg",
        religion:'orthodox',
        gender:"male",
        department:4,
        major:"Major",
        minor:"Minor",
        degree:"BA",
        cgpa:"3.56",
        college:"Standard college",
        qualification:"Linear",
        experience:2,
        salary:6789.23,
        contract_type:"PERMANENT",
        tin_number:"007875432",
        phone:"+2519235678",
        emergency_phone:"+2519567823",
        marital_status:"single",
        current_address:1,
        permanent_address:2,
        bank_account:1,
        facebook_account:"facebook url",
        twitter_account:"twitter url",
        linkedin_account:"linkedin url",
        instagram_account:"instagram url",
        date_of_birth:"2000-03-12",
        birth_place:"Addis Ababa",
        status:"sucess",
        role:1,
        updated_at: "2023-05-12",
        created_at:"2022-01-23"


    },
    {
        id:19,
        username:"DAR/1141/15",
        profile_pic: "/assets/images/avatars/avatar_19.jpg",
        religion:'orthodox',
        gender:"female",
        department:4,
        major:"Major",
        minor:"Minor",
        degree:"BA",
        cgpa:"3.56",
        college:"Standard college",
        qualification:"Linear",
        experience:2,
        salary:6789.23,
        contract_type:"PERMANENT",
        tin_number:"007875432",
        phone:"+2519235678",
        emergency_phone:"+2519567823",
        marital_status:"single",
        current_address:1,
        permanent_address:2,
        bank_account:1,
        facebook_account:"facebook url",
        twitter_account:"twitter url",
        linkedin_account:"linkedin url",
        instagram_account:"instagram url",
        date_of_birth:"2000-03-12",
        birth_place:"Addis Ababa",
        status:"banned",
        role:1,
        updated_at: "2023-05-12",
        created_at:"2022-01-23"


    },
    {
        id:20,
        username:"DAR/1142/15",
        profile_pic: "/assets/images/avatars/avatar_20.jpg",
        religion:'orthodox',
        gender:"male",
        department:4,
        major:"Major",
        minor:"Minor",
        degree:"BA",
        cgpa:"3.56",
        college:"Standard college",
        qualification:"Linear",
        experience:2,
        salary:6789.23,
        contract_type:"PERMANENT",
        tin_number:"007875432",
        phone:"+2519235678",
        emergency_phone:"+2519567823",
        marital_status:"single",
        current_address:1,
        permanent_address:2,
        bank_account:1,
        facebook_account:"facebook url",
        twitter_account:"twitter url",
        linkedin_account:"linkedin url",
        instagram_account:"instagram url",
        date_of_birth:"2000-03-12",
        birth_place:"Addis Ababa",
        status:"banned",
        role:1,
        updated_at: "2023-05-12",
        created_at:"2022-01-23"


    },
    {
        id:21,
        username:"DAR/1143/15",
        profile_pic: "/assets/images/avatars/avatar_24.jpg",
        religion:'orthodox',
        gender:"male",
        department:4,
        major:"Major",
        minor:"Minor",
        degree:"BA",
        cgpa:"3.56",
        college:"Standard college",
        qualification:"Linear",
        experience:2,
        salary:6789.23,
        contract_type:"PERMANENT",
        tin_number:"007875432",
        phone:"+2519235678",
        emergency_phone:"+2519567823",
        marital_status:"single",
        current_address:1,
        permanent_address:2,
        bank_account:1,
        facebook_account:"facebook url",
        twitter_account:"twitter url",
        linkedin_account:"linkedin url",
        instagram_account:"instagram url",
        date_of_birth:"2000-03-12",
        birth_place:"Addis Ababa",
        status:"banned",
        role:1,
        updated_at: "2023-05-12",
        created_at:"2022-01-23"


    },
    {
        id:22,
        username:"DAR/1144/15",
        profile_pic: "/assets/images/avatars/avatar_1.jpg",
        religion:'orthodox',
        gender:"male",
        department:4,
        major:"Major",
        minor:"Minor",
        degree:"BA",
        cgpa:"3.56",
        college:"Standard college",
        qualification:"Linear",
        experience:2,
        salary:6789.23,
        contract_type:"PERMANENT",
        tin_number:"007875432",
        phone:"+2519235678",
        emergency_phone:"+2519567823",
        marital_status:"single",
        current_address:1,
        permanent_address:2,
        bank_account:1,
        facebook_account:"facebook url",
        twitter_account:"twitter url",
        linkedin_account:"linkedin url",
        instagram_account:"instagram url",
        date_of_birth:"2000-03-12",
        birth_place:"Addis Ababa",
        status:"banned",
        role:1,
        updated_at: "2023-05-12",
        created_at:"2022-01-23"


    },
    {
        id:23,
        username:"DAR/1145/15",
        profile_pic: "/assets/images/avatars/avatar_2.jpg",
        religion:'orthodox',
        gender:"male",
        email:"email@gmail.com",
        department:4,
        major:"Major",
        minor:"Minor",
        degree:"BA",
        cgpa:"3.56",
        college:"Standard college",
        qualification:"Linear",
        experience:2,
        salary:6789.23,
        contract_type:"PERMANENT",
        tin_number:"007875432",
        phone:"+2519235678",
        emergency_phone:"+2519567823",
        marital_status:"single",
        current_address:1,
        permanent_address:2,
        bank_account:1,
        facebook_account:"facebook url",
        twitter_account:"twitter url",
        linkedin_account:"linkedin url",
        instagram_account:"instagram url",
        date_of_birth:"2000-03-12",
        birth_place:"Addis Ababa",
        status:"banned",
        role:1,
        updated_at: "2023-05-12",
        created_at:"2022-01-23"


    },
    {
        id:24,
        username:"DAR/1146/15",
        profile_pic: "/assets/images/avatars/avatar_12.jpg",
        religion:'orthodox',
        gender:"male",
        department:4,
        major:"Major",
        minor:"Minor",
        degree:"BA",
        cgpa:"3.56",
        college:"Standard college",
        qualification:"Linear",
        experience:2,
        salary:6789.23,
        contract_type:"PERMANENT",
        tin_number:"007875432",
        phone:"+2519235678",
        emergency_phone:"+2519567823",
        marital_status:"single",
        current_address:1,
        permanent_address:2,
        bank_account:1,
        facebook_account:"facebook url",
        twitter_account:"twitter url",
        linkedin_account:"linkedin url",
        instagram_account:"instagram url",
        date_of_birth:"2000-03-12",
        birth_place:"Addis Ababa",
        status:"banned",
        role:1,
        updated_at: "2023-05-12",
        created_at:"2022-01-23"


    },
    {
        id:25,
        username:"DAR/1147/15",
        password:"password",
        profile_pic: "/assets/images/avatars/avatar_23.jpg",
        religion:'orthodox',
        gender:"male",
        email:"email@gmail.com",
        department:4,
        major:"Major",
        minor:"Minor",
        degree:"BA",
        cgpa:"3.56",
        college:"Standard college",
        qualification:"Linear",
        experience:2,
        salary:10000.23,
        contract_type:"PERMANENT",
        tin_number:"007875432",
        phone:"+2519235678",
        emergency_phone:"+2519567823",
        marital_status:"single",
        current_address:11,
        permanent_address:12,
        bank_account:2,
        facebook_account:"facebook url",
        twitter_account:"twitter url",
        linkedin_account:"linkedin url",
        instagram_account:"instagram url",
        date_of_birth:"2000-03-12",
        birth_place:"Addis Ababa",
        status:"sucess",
        role:2,
        updated_at: "2023-05-12",
        created_at:"2022-01-23"


    },
    {
        id:26,
        username:"DAR/1148/15",
        first_name:"Abebe",
        middle_name:"Kebede",
        last_name:"Amanuel",
        profile_pic: "/assets/images/avatars/avatar_22.jpg",
        religion:'orthodox',
        gender:"male",
        email:"email@gmail.com",
        department:4,
        major:"Major",
        minor:"Minor",
        degree:"BA",
        cgpa:"3.56",
        college:"Standard college",
        qualification:"Linear",
        experience:2,
        salary:6789.23,
        contract_type:"PERMANENT",
        tin_number:"007875432",
        phone:"+2519235678",
        emergency_phone:"+2519567823",
        marital_status:"single",
        current_address:1,
        permanent_address:2,
        bank_account:1,
        facebook_account:"facebook url",
        twitter_account:"twitter url",
        linkedin_account:"linkedin url",
        instagram_account:"instagram url",
        date_of_birth:"2000-03-12",
        birth_place:"Addis Ababa",
        status:"banned",
        role:1,
        updated_at: "2023-05-12",
        created_at:"2022-01-23"

    },
    {
        id:27,
        username:"DAR/1149/15",
        first_name:"Abebe",
        middle_name:"Kebede",
        last_name:"Amanuel",
        profile_pic: "/assets/images/avatars/avatar_22.jpg",
        religion:'orthodox',
        gender:"male",
        email:"email@gmail.com",
        department:4,
        major:"Major",
        minor:"Minor",
        degree:"BA",
        cgpa:"3.56",
        college:"Standard college",
        qualification:"Linear",
        experience:2,
        salary:6789.23,
        contract_type:"PERMANENT",
        tin_number:"007875432",
        phone:"+2519235678",
        emergency_phone:"+2519567823",
        marital_status:"single",
        current_address:1,
        permanent_address:2,
        bank_account:1,
        facebook_account:"facebook url",
        twitter_account:"twitter url",
        linkedin_account:"linkedin url",
        instagram_account:"instagram url",
        date_of_birth:"2000-03-12",
        birth_place:"Addis Ababa",
        status:"banned",
        role:1,
        updated_at: "2023-05-12",
        created_at:"2022-01-23"


    },
    {
        id:28,
        username:"DAR/1150/15",
        first_name:"Abebe",
        middle_name:"Kebede",
        last_name:"Amanuel",
        profile_pic: "/assets/images/avatars/avatar_22.jpg",
        religion:'orthodox',
        gender:"male",
        email:"email@gmail.com",
        department:4,
        major:"Major",
        minor:"Minor",
        degree:"BA",
        cgpa:"3.56",
        college:"Standard college",
        qualification:"Linear",
        experience:2,
        salary:6789.23,
        contract_type:"PERMANENT",
        tin_number:"007875432",
        phone:"+2519235678",
        emergency_phone:"+2519567823",
        marital_status:"single",
        current_address:1,
        permanent_address:2,
        bank_account:1,
        facebook_account:"facebook url",
        twitter_account:"twitter url",
        linkedin_account:"linkedin url",
        instagram_account:"instagram url",
        date_of_birth:"2000-03-12",
        birth_place:"Addis Ababa",
        status:"banned",
        role:1,
        updated_at: "2023-05-12",
        created_at:"2022-01-23"


    },
    {
        id:29,
        username:"DAR/1151/15",
        password:"password",
        first_name:"Abebe",
        middle_name:"Kebede",
        last_name:"Amanuel",
        profile_pic: "/assets/images/avatars/avatar_22.jpg",
        religion:'orthodox',
        gender:"male",
        email:"email@gmail.com",
        department:4,
        major:"Major",
        minor:"Minor",
        degree:"BA",
        cgpa:"3.56",
        college:"Standard college",
        qualification:"Linear",
        experience:2,
        salary:6789.23,
        contract_type:"PERMANENT",
        tin_number:"007875432",
        phone:"+2519235678",
        emergency_phone:"+2519567823",
        marital_status:"single",
        current_address:1,
        permanent_address:2,
        bank_account:1,
        facebook_account:"facebook url",
        twitter_account:"twitter url",
        linkedin_account:"linkedin url",
        instagram_account:"instagram url",
        date_of_birth:"2000-03-12",
        birth_place:"Addis Ababa",
        status:"success",
        role:1,
        updated_at: "2023-05-12",
        created_at:"2022-01-23"


    },
    {
        id:30,
        username:"DAR/1152/15",
        password:"password",
        first_name:"Abebe",
        middle_name:"Kebede",
        last_name:"Amanuel",
        profile_pic: "/assets/images/avatars/avatar_22.jpg",
        religion:'orthodox',
        gender:"male",
        email:"email@gmail.com",
        department:4,
        major:"Major",
        minor:"Minor",
        degree:"BA",
        cgpa:"3.56",
        college:"Standard college",
        qualification:"Linear",
        experience:2,
        salary:6789.23,
        contract_type:"PERMANENT",
        tin_number:"007875432",
        phone:"+2519235678",
        emergency_phone:"+2519567823",
        marital_status:"single",
        current_address:1,
        permanent_address:2,
        bank_account:1,
        facebook_account:"facebook url",
        twitter_account:"twitter url",
        linkedin_account:"linkedin url",
        instagram_account:"instagram url",
        date_of_birth:"2000-03-12",
        birth_place:"Addis Ababa",
        status:"banned",
        role:1,
        updated_at: "2023-05-12",
        created_at:"2022-01-23"


    },
]
export default TeacherList;
